name: rowly
description: A production-grade, premium performance cross-platform CSV Viewer and Editor.
version: 1.1.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Architecture
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3

  # UI Foundation
  cupertino_icons: ^1.0.6

  # Utilities & Performance Optimization
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Static Analysis Tools
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true